server:
  port: 8081

spring:
  application:
    name: user

  cloud:
    openfeign:
      okhttp:
        enabled: true

  datasource:
    url: jdbc:mysql://localhost:3306/userdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: TestdbRoot
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    defer-datasource-initialization: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
          time_zone: Asia/Seoul
        order_inserts: true
        order_updates: true
        format_sql: true
        use_sql_comments: true

jwt:
  secret: JeTB8C1PYXBB4/A9/jas5gVmvZBxyw/7O8Ca4eizk2Q=

client:
  account: http://localhost:8082
  stock: http://localhost:8083

