@baseUrl=http://localhost:8082/api/accounts

### create account
POST {{baseUrl}}
Content-Type: application/json

{
  "username": "user1",
  "userid": 1,
  "passwd": "123456"
}

### create account
POST {{baseUrl}}
Content-Type: application/json

{
  "username": "user2",
  "userid": 2,
  "passwd": "123456"
}

### deposit
PUT {{baseUrl}}/1?amount=2000

### withdrawal
PATCH {{baseUrl}}/1
Content-Type: application/json

{
  "userid": 1,
  "amount": 1000,
  "passwd": "123456"
}


### account info
GET {{baseUrl}}/1