@baseUrl=http://localhost:8082/api/accounts

### deposit
PUT {{baseUrl}}/1?amount=2000

### withdrawal
PATCH {{baseUrl}}/1
Content-Type: application/json

{
  "userid": 1,
  "amount": 1000,
  "passwd": "123456"
}