@baseUrl=http://localhost:8083/internal/stocks

### create stock
POST {{baseUrl}}
Content-Type: application/json

{
  "cnt": 1,
  "price": 120000,
  "userid": 1
}

### create account
POST {{baseUrl}}
Content-Type: application/json

{
  "cnt": 1,
  "price": 120000,
  "userid": 2
}


### stock info
GET {{baseUrl}}/1