### variable
@baseUrl=http://localhost:8081/api/users

### regist user
POST {{baseUrl}}
Content-Type: application/json

{
  "email": "user3@test.com",
  "passwd": "password123",
  "name": "user3"
}


### login
POST {{baseUrl}}/login
Content-Type: application/x-www-form-urlencoded

username = admin@test.com &
password = password123

> {%
    client.global.set("auth_token", response.body.accessToken);
%}


### user info
GET {{baseUrl}}/3
Authorization: Bearer {{auth_token}}

### hello~
GET {{baseUrl}}/hello
Authorization: Bearer {{auth_token}}

